export const GET_ALL_ADMINS = "GET_ALL_ADMINS";
export const GET_ALL_ADMINS_SUCCESS = "GET_ALL_ADMINS_SUCCESS";
export const GET_ALL_ADMINS_FAILED = "GET_ALL_ADMINS_FAILED";
export const GET_ALL_ADMINS_RESET = "GET_ALL_ADMINS_RESET";

export const UPDATE_ADMIN = "UPDATE_ADMIN";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_FAILED = "UPDATE_ADMIN_FAILED";
export const UPDATE_ADMIN_RESET = "UPDATE_ADMIN_RESET";

export const DELETE_ADMIN = "DELETE_ADMIN";
export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
export const DELETE_ADMIN_FAILED = "DELETE_ADMIN_FAILED";
export const DELETE_ADMIN_RESET = "DELETE_ADMIN_RESET";