export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAILED = "GET_ALL_CATEGORIES_FAILED";
export const GET_ALL_CATEGORIES_RESET = "GET_ALL_CATEGORIES_RESET";

export const GET_CATEGORY_DETAIL = "GET_CATEGORY_DETAIL";
export const GET_CATEGORY_DETAIL_SUCCESS = "GET_CATEGORY_DETAIL_SUCCESS";
export const GET_CATEGORY_DETAIL_FAILED = "GET_CATEGORY_DETAIL_FAILED";
export const GET_CATEGORY_DETAIL_RESET = "GET_CATEGORY_DETAIL_RESET";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILED = "CREATE_CATEGORY_FAILED";
export const CREATE_CATEGORY_RESET = "CREATE_CATEGORY_RESET";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILED = "UPDATE_CATEGORY_FAILED";
export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";
export const DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET";