export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const GET_ALL_TRANSACTIONS_SUCCESS = "GET_ALL_TRANSACTIONS_SUCCESS";
export const GET_ALL_TRANSACTIONS_FAILED = "GET_ALL_TRANSACTIONS_FAILED";
export const GET_ALL_TRANSACTIONS_RESET = "GET_ALL_TRANSACTIONS_RESET";

export const GET_TRANSACTION_DETAIL = "GET_TRANSACTION_DETAIL";
export const GET_TRANSACTION_DETAIL_SUCCESS = "GET_TRANSACTION_DETAIL_SUCCESS";
export const GET_TRANSACTION_DETAIL_FAILED = "GET_TRANSACTION_DETAIL_FAILED";
export const GET_TRANSACTION_DETAIL_RESET = "GET_TRANSACTION_DETAIL_RESET";

export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_FAILED = "CREATE_TRANSACTION_FAILED";
export const CREATE_TRANSACTION_RESET = "CREATE_TRANSACTION_RESET";

export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAILED = "DELETE_TRANSACTION_FAILED";
export const DELETE_TRANSACTION_RESET = "DELETE_TRANSACTION_RESET";