export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_RESET = "LOGIN_RESET";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_RESET = "REGISTER_RESET";

export const ADMIN_FETCH = "ADMIN_FETCH";
export const ADMIN_FETCH_SUCCESS = "ADMIN_FETCH_SUCCESS";
export const ADMIN_FETCH_FAILED = "ADMIN_FETCH_FAILED";
export const ADMIN_FETCH_RESET = "ADMIN_FETCH_RESET";

export const ADMIN_UPDATE = "ADMIN_UPDATE";
export const ADMIN_UPDATE_SUCCESS = "ADMIN_UPDATE_SUCCESS";
export const ADMIN_UPDATE_FAILED = "ADMIN_UPDATE_FAILED";
export const ADMIN_UPDATE_RESET = "ADMIN_UPDATE_RESET";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const LOGOUT_RESET = "LOGOUT_RESET";